In [2]:
import numpy as np
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Flatten
from tensorflow.keras.layers import Embedding

reviews = ['nice food',
        'amazing restaurant',
        'too good',
        'just loved it!',
        'will go again',
        'horrible food',
        'never go there',
        'poor service',
        'poor quality',
        'needs improvement']

sentiment = np.array([1,1,1,1,1,0,0,0,0,0])

In [5]:
one_hot("amazing restaurant",30)

[20, 1]

In [8]:
vocab_size = 30
encoded_reviews = [one_hot(d, vocab_size) for d in reviews]
encoded_reviews

[[16, 3],
 [20, 1],
 [24, 21],
 [7, 4, 9],
 [2, 5, 8],
 [23, 3],
 [3, 5, 21],
 [14, 24],
 [14, 27],
 [4, 8]]

In [10]:
max_length = 3
paded_reviews = pad_sequences(encoded_reviews, maxlen = max_length, padding='post')
paded_reviews

array([[16,  3,  0],
       [20,  1,  0],
       [24, 21,  0],
       [ 7,  4,  9],
       [ 2,  5,  8],
       [23,  3,  0],
       [ 3,  5, 21],
       [14, 24,  0],
       [14, 27,  0],
       [ 4,  8,  0]], dtype=int32)

In [13]:
embeded_vector_size = 5

model = Sequential()
model.add(Embedding(vocab_size, embeded_vector_size, input_length = max_length, name = "embedding"))
model.add(Flatten())
model.add(Dense(1, activation='sigmoid'))

In [14]:
X = paded_reviews
y = sentiment

In [15]:
 model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
 )

In [16]:
model.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 3, 5)              150       
                                                                 
 flatten (Flatten)           (None, 15)                0         
                                                                 
 dense (Dense)               (None, 1)                 16        
                                                                 
Total params: 166 (664.00 Byte)
Trainable params: 166 (664.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [17]:
model.fit(X, y, epochs=50, verbose=0)

In [19]:
loss, accuracy = model.evaluate(X,y)
accuracy

1/1 [==============================] - 0s 24ms/step - loss: 0.6297 - accuracy: 1.0000


1.0

In [20]:
model.get_layer('embedding').get_weights()[0]

array([[ 0.09342737,  0.09291108,  0.03036971, -0.00969615, -0.05964839],
       [-0.07634741, -0.06868006, -0.00936305,  0.09321675, -0.00187345],
       [-0.06372476,  0.00520382, -0.04531765, -0.10054096, -0.00562558],
       [ 0.03282985, -0.04516471,  0.07938059,  0.10100482,  0.048384  ],
       [ 0.03532971, -0.09895296, -0.03288458,  0.00101786, -0.04138849],
       [ 0.032402  ,  0.02314623, -0.02035825, -0.04347807,  0.01843843],
       [ 0.01436856, -0.0070797 , -0.02051631, -0.01188214,  0.04203484],
       [-0.00638219,  0.00810039, -0.00811588, -0.07487875, -0.09488289],
       [ 0.02334901,  0.01708988,  0.09682509, -0.02184908,  0.057929  ],
       [-0.04663461, -0.01531815, -0.0085336 ,  0.07508282,  0.03144449],
       [ 0.02893623,  0.04476497, -0.02624821, -0.04249216, -0.02921681],
       [-0.00826418, -0.03195257, -0.02750131,  0.04009842, -0.01107594],
       [ 0.01193165,  0.04443915,  0.02404107,  0.00602882,  0.01397561],
       [-0.02054503,  0.00111163,  0.0

In [21]:
weights = model.get_layer('embedding').get_weights()[0]
len(weights)

30

In [22]:
weights[16]

array([-0.06160221,  0.09136118, -0.06831039, -0.04288852, -0.09215659],
      dtype=float32)

In [23]:
weights[20]

array([-0.03656122,  0.06958515, -0.02920083, -0.02882858, -0.01525204],
      dtype=float32)